### ISSUE TITLE
This is exactly what I was looking for. However, i'm gettign this issue. any help would appreciated.

### ISSUE THREAD

**Issue by 6am** [JavaGarcia/wpjs#1]
Error: This socket is closed.
   at Socket._writeGeneric (net.js:640:19)
   at Socket._write (net.js:694:8)
   at doWrite (_stream_writable.js:292:12)
   at writeOrBuffer (_stream_writable.js:278:5)
   at Socket.Writable.write (_stream_writable.js:207:11)
   at Socket.write (net.js:618:40)
   at EventEmitter.send (/home/ubuntu/wpjs/index.js:18:20)
   at /home/ubuntu/wpjs/teste.js:14:8
   at Layer.handle [as handle_request] (/home/ubuntu/wpjs/node_modules/express/lib/router/layer.js:95:5)
   at next (/home/ubuntu/wpjs/node_modules/express/lib/router/route.js:131:13)

**Comment by JavaGarcia** [comment]
Hi,
Can you share me your file teste.js?

**Comment by 6am** [comment]
var express = require('express');
var app = express();
var server = require('http').createServer(app);
var io = require('socket.io').listen(server); 
var wpjs = require('./index.js');


wpjs.connect({number: '55110000000', password: '0000000000000000000=', yowsup:"/home/ubuntu/yowsup"}, function(state){
     console.log(state)
console.log('teste');
 }); 

wpjs.send({to: '5511999768557', type: 'txt', data: 'Im busy...'}); 
 

console.log(wpjs);

wpjs.on('inbox',function(message){
  console.log(message.type)//type of message (txt)
  console.log(message.from)// number_src of message
  console.log(message.username) // nickname 
  console.log(message.date)// arrival date
  console.log(message.data)// message...
});  

app.get('/', function (req, res) {
  res.send('Hello World!');
});

app.get('/send', function (req, res,wpjs) {
    wpjs.connect({number: '55110000000', password: '0000000000000000000=', yowsup:"/home/ubuntu/yowsup"}, function(state){
     console.log(state)
    }); 

      wpjs.send({to: '5511999768557', type: 'txt', data: 'Im busy...'}); 
      res.send('SEND');
  
 
});

server.listen(3000, function () {
  console.log('Example app listening on port 3000!');
});

**Comment by 6am** [comment]
Phone and password have been changed. Thank you for your quick reply :)

**Comment by 6am** [comment]
For anyone who is starting, here is a working example: 

var wpjs = require('./index.js');

wpjs.connect({number: ‘00000000000’, password: ’000=’, yowsup:"/home/ubuntu/yowsup/yowsup-cli"}, function(state){
 console.log(state);

	wpjs.send({to: ‘00000000’, type: 'txt', data: 'Im online…’}); 

	wpjs.on('inbox',function(message){
 		console.log('[INBOX] User:'+message.username+' from:'+message.from+' data: '+message.data);
		 wpjs.send({to: message.from, type: 'txt', data: message.data}); 
	}); 

});

**Comment by 6am** [comment]
thank you Java!
