### ISSUE TITLE
Socket is breaking on receiving EMOJIs

### ISSUE THREAD

**Issue by 6am** [JavaGarcia/wpjs#2]
Do you have anytips on how to handle it? 

Thank you in advance

**Comment by JavaGarcia** [comment]
Can you share to me the error? 😐

**Comment by JavaGarcia** [comment]
Can you share me the error?

**Comment by 6am** [comment]
Sure.. 

![image](https://cloud.githubusercontent.com/assets/4224539/23677604/906d9daa-035f-11e7-9786-7e92ef94b0bd.png)

I doesnt "send" ..


wpjs.connect({number: '*', password: '*', yowsup:"/home/ubuntu/yowsup/yowsup-cli"}, function(state){
    wpjs.send({to: '*', type: 'txt', data: 'Online test EMOJI \ue054'});  //it does send the emoji

	//on message received
    wpjs.on('inbox',function(message){		
//echo the text
//it does echo if no EMOJI
		console.log('[INBOX] User:'+message.username+' from:'+message.from+' data: '+message.data);
// 		wpjs.send({to: message.from, type: 'txt', data: message.data}); 

     
    }); 

});


And after an emoji, it stops receiving every msg, I need to restart the node.

Thank you

**Comment by 6am** [comment]
When displaying the object inMsj I can see that this is the error. 

UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f600' in position 0: ordinal not in range(128)

**Comment by 6am** [comment]
MESSAGE = messageOut.encode('latin-1').decode() if sys.version_info >= (3, 0) else messageOut.encode('utf-8'), 

on line 511 of layer.py did solved the issue! :) thank you again for your time.
